# Generated by Django 2.0.3 on 2018-04-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_name', models.CharField(blank=True, max_length=64)),
                ('coach_image', models.ImageField(blank=True, upload_to='stuff_image')),
            ],
        ),
    ]
