# Generated by Django 2.0.3 on 2018-04-28 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_coaches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tplan',
            name='Athletes_name',
        ),
    ]
