# Generated by Django 2.0.3 on 2018-04-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_remove_tplan_athletes_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tplan',
            name='Athletes_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
