# Generated by Django 2.0.3 on 2018-04-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_tplan_athletes_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tplan',
            name='friday',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tplan',
            name='monday',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tplan',
            name='saturday',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tplan',
            name='sunday',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tplan',
            name='thursday',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tplan',
            name='tuesday',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tplan',
            name='wednesday',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
