# Generated by Django 2.0.3 on 2018-04-28 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_auto_20180428_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tplan',
            old_name='friday',
            new_name='friday_pratice',
        ),
        migrations.RenameField(
            model_name='tplan',
            old_name='monday',
            new_name='monday_pratice',
        ),
        migrations.RenameField(
            model_name='tplan',
            old_name='saturday',
            new_name='saturday_pratice',
        ),
        migrations.RenameField(
            model_name='tplan',
            old_name='sunday',
            new_name='sunday_pratice',
        ),
        migrations.RenameField(
            model_name='tplan',
            old_name='thursday',
            new_name='thursday_pratice',
        ),
        migrations.RenameField(
            model_name='tplan',
            old_name='tuesday',
            new_name='tuesday_pratice',
        ),
        migrations.RenameField(
            model_name='tplan',
            old_name='wednesday',
            new_name='wednesday_pratice',
        ),
        migrations.RemoveField(
            model_name='tplan',
            name='practice_day',
        ),
    ]
