# Generated by Django 2.0.3 on 2018-04-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_auto_20180428_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tplan',
            old_name='friday_pratice',
            new_name='friday_practice',
        ),
        migrations.RenameField(
            model_name='tplan',
            old_name='monday_pratice',
            new_name='monday_practice',
        ),
        migrations.RenameField(
            model_name='tplan',
            old_name='saturday_pratice',
            new_name='saturday_practice',
        ),
        migrations.RenameField(
            model_name='tplan',
            old_name='sunday_pratice',
            new_name='sunday_practice',
        ),
        migrations.RenameField(
            model_name='tplan',
            old_name='thursday_pratice',
            new_name='thursday_practice',
        ),
        migrations.RenameField(
            model_name='tplan',
            old_name='tuesday_pratice',
            new_name='tuesday_practice',
        ),
        migrations.RenameField(
            model_name='tplan',
            old_name='wednesday_pratice',
            new_name='wednesday_practice',
        ),
    ]
