# Generated by Django 2.0.3 on 2018-04-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0007_auto_20180428_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
