# Generated by Django 2.0.3 on 2018-04-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0009_remove_tplan_practice_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tplan',
            name='user',
        ),
    ]
