# Generated by Django 2.0.3 on 2018-04-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0010_remove_tplan_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tplan',
            old_name='start_date',
            new_name='week_start_date',
        ),
    ]
