# Generated by Django 2.0.3 on 2018-04-29 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0011_auto_20180429_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='tplan',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coach.Profile'),
            preserve_default=False,
        ),
    ]
