# Generated by Django 2.0.3 on 2018-04-30 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0012_tplan_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tplan',
            name='Athletes_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tplan',
            name='friday_practice',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tplan',
            name='monday_practice',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tplan',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coach.Profile'),
        ),
        migrations.AlterField(
            model_name='tplan',
            name='saturday_practice',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tplan',
            name='sunday_practice',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tplan',
            name='thursday_practice',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tplan',
            name='tuesday_practice',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tplan',
            name='wednesday_practice',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tplan',
            name='week_start_date',
            field=models.DateField(max_length=200),
        ),
    ]
