# Generated by Django 2.0.3 on 2018-04-30 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0013_auto_20180430_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tplan',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coach.Profile'),
        ),
    ]
