# Generated by Django 2.0.3 on 2018-05-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0015_auto_20180430_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('see_private_plan', 'Can see private plan'), ('see_coach_access', 'Can see coach access'))},
        ),
    ]
