# Generated by Django 2.0.3 on 2018-05-02 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0016_auto_20180501_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='charge_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=234),
            preserve_default=False,
        ),
    ]
