# Generated by Django 2.0.3 on 2018-05-02 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0017_profile_charge_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(blank=True, max_length=200)),
                ('week_start_date', models.DateField(max_length=200)),
                ('Athletes_name', models.CharField(max_length=30)),
                ('monday_practice', models.CharField(max_length=200)),
                ('tuesday_practice', models.CharField(max_length=200)),
                ('wednesday_practice', models.CharField(max_length=200)),
                ('thursday_practice', models.CharField(max_length=200)),
                ('friday_practice', models.CharField(max_length=200)),
                ('saturday_practice', models.CharField(max_length=200)),
                ('sunday_practice', models.CharField(max_length=200)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coach.Profile')),
            ],
        ),
    ]
