# Generated by Django 2.0.3 on 2018-05-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0019_auto_20180502_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='charge_id',
            field=models.CharField(max_length=234, null=True),
        ),
    ]
