# Generated by Django 2.0.3 on 2018-05-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0020_auto_20180504_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='charge_id',
            field=models.CharField(blank=True, max_length=234, null=True),
        ),
    ]
