# Generated by Django 2.0.3 on 2018-05-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0025_siteadmin_premium_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteadmin',
            name='email_field',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
